# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: test deploy
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
jobs:
  test-deploy:
    name: deploy
    timeout-minutes: 7
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          - nspawn-docker
          - nspawn-podman
          - docker-docker
          - podman-podman
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: test docker deploy to nspawn
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          case "${PLATFORM}" in
            nspawn-docker)
              bin/test-nspawn.sh
            ;;
            nspawn-podman)
              CONTENGI='podman' bin/test-nspawn.sh
            ;;
            docker-docker)
              bin/test-docker.sh
            ;;
            podman-podman)
              sudo cp -vf ansible/files/etc/sudoers /etc/sudoers
              CONAME='pdm4ans' CONTENGI='podman' sudo bin/test-docker.sh
            ;;
            *)
              echo "wrong [${PLATFORM}] platform"
              exit 1
            ;;
          esac
  linters:
    name: linters
    timeout-minutes: 11
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: lint the repo
        env:
          BRA: master
        run: |
          curl -sL \
          https://raw.githubusercontent.com/raven428/container-images/refs/heads/${{
          env.BRA }}/sources/linters-ubuntu-22_04/check-dir.sh | bash
          curl -sL \
          https://raw.githubusercontent.com/raven428/container-images/refs/heads/${{
          env.BRA }}/sources/ansible-ubuntu/check-dir.sh | bash
  MegaLinter:
    name: MegaLinter
    timeout-minutes: 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: MegaLinter
        uses: oxsecurity/megalinter@v9
        env:
          VALIDATE_ALL_CODEBASE: true
  all-green:
    name: all green
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - test-deploy
      - linters
      - MegaLinter
    if: always()
    permissions:
      checks: read
    steps:
      - name: waiting for checks success
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: all green, foobar
          timeout: 111s
